"""initial schema

Revision ID: a8e45e5127c2
Revises: 
Create Date: 2026-08-14 22:12:35.982099
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# Custom column types (GUID, UTCDateTime) are rendered as app.core.db.<Type>.
import app.core.db  # noqa: F401
from alembic import op

revision: str = 'a8e45e5127c2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_resources',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('resource_group', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('latency_p95_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_pct', sa.Float(), nullable=False),
    sa.Column('throughput_rpm', sa.Float(), nullable=False),
    sa.Column('quota_used_pct', sa.Float(), nullable=True),
    sa.Column('last_checked_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('azure_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_azure_resources_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_azure_resources_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_azure_resources_status'), ['status'], unique=False)

    op.create_table('budgets',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('evaluation_datasets',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_name'), ['name'], unique=True)

    op.create_table('guardrail_policies',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detect_prompt_injection', sa.Boolean(), nullable=False),
    sa.Column('redact_pii', sa.Boolean(), nullable=False),
    sa.Column('block_on_injection', sa.Boolean(), nullable=False),
    sa.Column('max_input_chars', sa.Integer(), nullable=False),
    sa.Column('banned_phrases', sa.JSON(), nullable=False),
    sa.Column('tool_allowlist', sa.JSON(), nullable=False),
    sa.Column('domain_allowlist', sa.JSON(), nullable=False),
    sa.Column('require_citations', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardrail_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrail_policies_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrail_policies_name'), ['name'], unique=True)

    op.create_table('health_metrics',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('component', sa.String(length=60), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_health_component_recorded', ['component', 'recorded_at'], unique=False)

    op.create_table('models',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('deployment_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('input_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('context_window > 0', name='ck_model_context_window'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'deployment_name', name='uq_model_provider_deployment')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_status'), ['status'], unique=False)

    op.create_table('rag_pipelines',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=120), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('reranking_enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_filters', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('chunk_size > chunk_overlap', name='ck_chunk_overlap_lt_size'),
    sa.CheckConstraint('top_k > 0', name='ck_top_k_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_pipelines_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_pipelines_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_team'), ['team'], unique=False)

    op.create_table('agents',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('fallback_model_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_pipeline_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('guardrail_policy_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('updated_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guardrail_policy_id'], ['guardrail_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rag_pipeline_id'], ['rag_pipelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_rag_pipeline_id'), ['rag_pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('acknowledged_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('actor_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_action', ['created_at', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)

    op.create_table('documents',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('pipeline_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('uploaded_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('indexed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['rag_pipelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('prompts',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('owner_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('active_version', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompts_owner_id'), ['owner_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_version', sa.Integer(), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('guardrail_outcome', sa.String(length=20), nullable=False),
    sa.Column('evaluation_score', sa.Float(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_runs_agent_created', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_agent_runs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('agent_versions',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_version')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('document_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunk_document_ordinal')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('dataset_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('aggregate_scores', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('regression_detected', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('triggered_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_status'), ['status'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('prompt_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('agent_run_steps',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_steps_run_id'), ['run_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_run_id'), ['run_id'], unique=False)

    op.create_table('guardrail_events',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('policy_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['guardrail_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardrail_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrail_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrail_events_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrail_events_run_id'), ['run_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('model_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_occurred_model', ['occurred_at', 'model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_team'), ['team'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_team'))
        batch_op.drop_index(batch_op.f('ix_usage_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_usage_records_model_name'))
        batch_op.drop_index(batch_op.f('ix_usage_records_agent_id'))
        batch_op.drop_index('ix_usage_occurred_model')

    op.drop_table('usage_records')
    with op.batch_alter_table('guardrail_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrail_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_guardrail_events_rule'))
        batch_op.drop_index(batch_op.f('ix_guardrail_events_created_at'))

    op.drop_table('guardrail_events')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_run_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_run_id'))

    op.drop_table('agent_run_steps')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_agent_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))

    op.drop_table('agent_versions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index('ix_agent_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_model_name'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_id'))
        batch_op.drop_index('ix_agent_runs_agent_created')

    op.drop_table('agent_runs')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_key'))
        batch_op.drop_index(batch_op.f('ix_prompts_deleted_at'))

    op.drop_table('prompts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_documents_filename'))
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_documents_checksum'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_created_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))

    op.drop_table('alerts')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index(batch_op.f('ix_agents_slug'))
        batch_op.drop_index(batch_op.f('ix_agents_rag_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index(batch_op.f('ix_agents_model_id'))
        batch_op.drop_index(batch_op.f('ix_agents_environment'))
        batch_op.drop_index(batch_op.f('ix_agents_deleted_at'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_team'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('rag_pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_pipelines_name'))
        batch_op.drop_index(batch_op.f('ix_rag_pipelines_deleted_at'))

    op.drop_table('rag_pipelines')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_status'))
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.drop_index(batch_op.f('ix_models_deleted_at'))

    op.drop_table('models')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_health_component_recorded')

    op.drop_table('health_metrics')
    with op.batch_alter_table('guardrail_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrail_policies_name'))
        batch_op.drop_index(batch_op.f('ix_guardrail_policies_deleted_at'))

    op.drop_table('guardrail_policies')
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_deleted_at'))

    op.drop_table('evaluation_datasets')
    op.drop_table('budgets')
    with op.batch_alter_table('azure_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_azure_resources_status'))
        batch_op.drop_index(batch_op.f('ix_azure_resources_resource_type'))
        batch_op.drop_index(batch_op.f('ix_azure_resources_name'))

    op.drop_table('azure_resources')
    # ### end Alembic commands ###
